# Generated by Django 2.2 on 2019-04-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190420_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
    ]
